env: development

http:
  enable: true
  host: 'localhost'
  port: 5000

https:
  enable: false
  port: 5001
  key: key.pem
  cert: certificate.pem

twitter:
	TWITTER_CONSUMER_KEY: ''
	TWITTER_CONSUMER_SECRET: ''
	TWITTER_ACCESS_TOKEN_KEY: ''
	TWITTER_ACCESS_TOKEN_SECRET: ''

instamojo:
	INSTAMOJO_URL: 'https://www.instamojo.com/api/1.1/links/'
	INSTAMOJO_API_KEY: ''
	INSTAMOJO_AUTH_TOKEN: ''

database:
	REDIS_URL: 'http://localhost:6379'