env: development

http:
  enable: true
  host: 'localhost'
  port: 5000

https:
  enable: false
  port: 5001
  key: key.pem
  cert: certificate.pem

twitter:
	TWITTER_CONSUMER_KEY: 'yEtXXuUVzcLj4JZk2vieAjJox'
	TWITTER_CONSUMER_SECRET: 'AAcUx0wajXJ49qkdrgN3dqhZpXGtysGBKY9EtZiieRraGX9wYl'
	TWITTER_ACCESS_TOKEN_KEY: '4306867274-Sg0NlHKYpc9bIwVH2xt2YAVp5asEwA93K1x1TUP'
	TWITTER_ACCESS_TOKEN_SECRET: 'LP8GtTMXKKmPGKuYo9LKI2Es0gcce8hrJpfOT5gyFintd'

instamojo:
	INSTAMOJO_URL: 'https://www.instamojo.com/api/1.1/links/'
	INSTAMOJO_API_KEY: 'a828edcaf75e5da3ce9582d05a5585c7'
	INSTAMOJO_AUTH_TOKEN: 'aef0907120c9fa7f53b7c6de98e4e84c'

database:
	REDIS_URL: 'http://localhost:6379'